# .github/workflows/simple-test.yml

name: Simple Test

on:
  push:
    branches:
      - main  # Runs on push to the main branch
      - branch1
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch
      - branch1

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      - name: Run simple test
        run: echo "This is a simple test."  # A basic command to test the workflow
